Basics

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([9.13645991e-01, 6.69532246e-01, 7.21215377e-04, 9.60465646e-01,
       5.69780958e-01])

In [13]:
np.random.rand(5, 5)

array([[0.63379964, 0.37883618, 0.75685332, 0.25115425, 0.21864982],
       [0.39899659, 0.43244187, 0.49153983, 0.8021334 , 0.12645072],
       [0.16728048, 0.38502617, 0.47111857, 0.62158757, 0.36265545],
       [0.17994256, 0.39890164, 0.5865935 , 0.69430963, 0.12496336],
       [0.66252973, 0.80780502, 0.06761216, 0.80728881, 0.29959308]])

In [14]:
np.random.randn(4)

array([-1.3115682 ,  0.85870948, -1.26121748, -1.68576455])

In [15]:
np.random.randn(5,5)

array([[-0.4055832 ,  0.06115862, -1.00089874,  1.6268705 ,  0.45575684],
       [ 1.33056408, -0.08665096,  0.90065263,  1.91084331,  0.30533382],
       [ 0.99494756, -0.01689041,  1.8018938 , -0.71543174, -0.54224385],
       [ 2.16740038,  0.23421   , -1.6658081 ,  2.12371551,  0.16731351],
       [ 0.53105622, -0.96772101, -0.19230689, -0.2892651 , -0.96382217]])

In [16]:
np.random.randint(1, 100)

90

In [17]:
np.random.randint(1, 100, 10)

array([54, 92, 19, 57, 26, 37, 71, 70, 77, 29])

In [18]:
arr = np.arange(25)
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
ranarr = np.random.randint(0,100, (5,5))
ranarr

array([[27, 56, 46, 41, 55],
       [71, 85,  1, 35, 80],
       [31,  9, 81, 52, 10],
       [75, 76,  7, 99, 75],
       [81, 24, 99, 52, 15]])

In [21]:
ranarr.min()

1

In [22]:
ranarr.max()

99

In [23]:
ranarr.argmax()

18

In [25]:
ranarr.argmin()

7

In [27]:
ranarr.shape

(5, 5)

In [29]:
ranarr.reshape((1, 25))

array([[27, 56, 46, 41, 55, 71, 85,  1, 35, 80, 31,  9, 81, 52, 10, 75,
        76,  7, 99, 75, 81, 24, 99, 52, 15]])

In [30]:
ranarr.dtype

dtype('int64')

Indexing and Slicing

In [31]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr[1:5]

array([1, 2, 3, 4])

In [33]:
arr[10]

10

In [34]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [35]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [40]:
arr = np.random.randint(1, 100, (5,5))
arr

array([[95, 96, 67, 93, 82],
       [13, 66, 46, 17, 90],
       [21, 28, 73, 50, 67],
       [79, 84,  9, 11, 77],
       [96, 98, 38, 96, 55]])

In [41]:
arr[:2,:2]

array([[95, 96],
       [13, 66]])

In [42]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
arr[arr >= 5]

array([ 5,  6,  7,  8,  9, 10])

In [46]:
arr2d = np.arange(50).reshape(5, 10)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [47]:
arr2d[2:4, 3:5]

array([[23, 24],
       [33, 34]])

Operations

In [48]:
arr = np.arange(0, 11)

In [49]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [50]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [51]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [52]:
arr / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [53]:
1 / arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [54]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [55]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [56]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [58]:
np.max(arr) == arr.max()
np.max(arr)

10

In [59]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [60]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])